### ISSUE TITLE
Installation and usage experience

### ISSUE THREAD

**Issue by janschulz** [aknutas/nails#12]
[This was part of https://github.com/openjournals/joss-reviews/issues/233] 

Installation was a bit of pain as the required packages are not in the install steps and so I tried a few times (on a new r install) until I had every package. Then I discovered the required package section... So while everything is there, for a "Product", the installation process was a bit of a pain. 

Another "problem" was that I put the ziped file into `./input` together with the unziped file and that resulted in a failure.

IMO the whole thing should become a package (=automatic installation of requirements) and the rmd file a functions which creates this file. Or even better one functions which takes filenames as input (zip or list of txt files), does the work on them and sends the content of the current rmd file to the knitr function.

**Comment by aknutas** [comment]
Creating a package would be more useful. We discussed the issue with the team and decided to do a package fork for nails in the future to allow people to better utilize nails. However, we cannot implement the change now, because it would require major refactoring.

For an intermediate solution we added a "startnails.sh" for GUI-less startup so that execution becomes more easier for manual testing and usage.

To address the zip issue we added a filename skip check for zip files.
