### ISSUE TITLE
NAs introduced by coercion

### ISSUE THREAD

**Issue by breakawaybilly** [aknutas/nails#18]
When I tried to run the exploration.Rmd I got an error message.

![image](https://user-images.githubusercontent.com/29048870/26855818-1efcaf96-4b15-11e7-9b41-72b3cf390516.png)

When I pulled the warnings from R I got the following errors. 

![image](https://user-images.githubusercontent.com/29048870/26855866-5599c82c-4b15-11e7-9d55-525fd9f9a6d8.png)

**Comment by aknutas** [comment]
I am sorry, but we have not been able to replicate this issue with our Linux server or *NIX-based development machines with any of the test datasets.

**Comment by jsalminen** [comment]
Hi,

The error is actually happening somewhere in cleaning2.R, which gets called on row 23 in exploration.Rmd. Row 19 refers to the first row of the block where an error occurred. I haven't been able to reproduce it either.

Warnings  happen probably on row 423 in cleaning2.R and if so they are expected behavior. The script is extracting publication years from reference list, and if a year is missing from a reference a NA will be introduced when trying to convert extracted string to a number.
