### ISSUE TITLE
CSV to ISI format error

### ISSUE THREAD

**Issue by daveedave** [aknutas/nails#22]
Hi,

At first I love you work and hope you can help me.
I tried to open the ISI-Format from WebOfScience convert it to CSV and then back to the tab-delimited format but couldn't get it working on the hammer site. Both tab-delimited files look the same but the converted version is not working. I used libreoffice and I am working on Ubuntu 16.04.

Thank you very much in advance
David
[WebOfScience.zip](https://github.com/aknutas/nails/files/1237224/WebOfScience.zip)

**Comment by jsalminen** [comment]
Hi David,

Thanks for the feedback! 

The problem here is that for some reason tab-delimited files from Web Of Science have an extra tab in the end of each line, which confuses standard functions used for reading data in R. See attached screenshot. Once you convert the data to another format and then back to tab-delimited, you get a properly formatted tab-delimited file, which is slightly different than the original. 

At the moment only tab-delimited data from Web of Science is supported, but we're planning to add more options.

Best,
Juho

![webofscienceconverted_txt_and_webofscienceoriginal_txt](https://user-images.githubusercontent.com/8121945/29577213-4c63ee50-8773-11e7-80f1-e950480e5f46.jpg)

**Comment by daveedave** [comment]
Hi Juho,

first of all thanks for the fast respond. 
I tried it again with adding that extra Tab at the end of the file and used https://www.diffchecker.com/diff to check for differences and it showed me that they are now completly identical but sadly it is still not working. I will add the new files again maybe it will help you fix the problem but i will close this thread for now.

Still Thanks for your help.

David
[WebOfScience.zip](https://github.com/aknutas/nails/files/1242818/WebOfScience.zip)
