### ISSUE TITLE
Error list

### ISSUE THREAD

**Issue by hbrueske** [aknutas/nails#25]
I tried to use your lit analysis service but I got below errors. It was an zipped, tab delimited file from web of science, core library.

**Comment by Stu-dem** [comment]
Hi there
I have also experienced a similar issue with an identical output to hbrueske's on a recent job - if the devs need i can supply links to the uploaded data and the outputted files.
Thanks!

**Comment by aknutas** [comment]
Web of Science changed their csv export format. We adapted in commit https://github.com/aknutas/nails/commit/94f30d45341773d2c4cce6c3bd3b61e41169760c and updated the server with the new software. This means that all old datasets do not work with the server.

I tested the server today with test data and it works. The issue is with the uploaded data. If you are having issues, please try re-downloading your dataset from WoS.
