### ISSUE TITLE
problem with HAMMER

### ISSUE THREAD

**Issue by gnschwarz** [aknutas/nails#5]
![capture](https://cloud.githubusercontent.com/assets/20034602/16181447/9a7602cc-3661-11e6-852c-1827a824b940.PNG)

**Comment by aknutas** [comment]
Unable to replicate. The issue is with the user dataset.

**Comment by jsalminen** [comment]
Could be due to wrong download format from Web of Science. Make sure to:
1. Select "Core Collection" from the search page
2. From download pop-up, select "Full record and references"
3. Download file format should be "Tab-delimited (Mac)" or "Tab-delimited (Win)

I don't have access to Web of Science at the moment, so I couldn't verify my guess, but the script tends to throw this kind of errors when some of the expected data columns are missing.

**Comment by arash-hajikhani** [comment]
I have tested now, perfectly running.
